<?php

namespace HC\Bundle\MediaBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\Query;

/**
 * EpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeRepository extends EntityRepository
{

    public function fetchEpisodes($start = 0, $count = NULL, $subscriptionId =  NULL, $dateFilter = NULL)
    {

//        $dql = 'SELECT e, s FROM HCMediaBundle:Episode e JOIN e.subscription s ';
//        if($subscriptionId !== NULL)
//            $dql .= ' WHERE (e.subscription = :subscriptionId)';
//        $dql .= ' ORDER BY e.pubDate DESC';
        var_dump($dateFilter);

        $dql = 'SELECT e, s FROM HCMediaBundle:Episode e JOIN e.subscription s ';
        if($subscriptionId !== NULL || $dateFilter !== NULL){
            $dql .= ' WHERE (e.subscription = :subscriptionId OR e.pubDate ';
            $dql .= $dateFilter['symbol'];
            $dql .= ' :dfValue)';

        }
        $dql .= ' ORDER BY e.pubDate DESC';

        $query = $this->getEntityManager()->createQuery($dql)
            ->setFirstResult($start)
            ->setMaxResults($count);

        if($subscriptionId !== NULL || $dateFilter !== NULL){
            $query->setParameters(array(
                'subscriptionId' => $subscriptionId,
                'dfValue' => $dateFilter['value']
            ));
        }

        $result = $query->getResult();
        return $result;
    }






}
