<?php

namespace HC\Bundle\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\Query;

/**
 * EpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeRepository extends EntityRepository
{

    public function findManyEpisodes($start, $count)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT e, m FROM HCMediaBundle:Episode e
        JOIN e.media m
        ORDER BY e.pubDate DESC'
            )
            ->setFirstResult($start)
            ->setMaxResults($count);

        try {
            $paginator = new Paginator($query, $fetchJoinCollection = true);
            return $paginator;

        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }


    public function findEpisodesByMedia($media, $start, $page_count)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT e, m FROM HCMediaBundle:Episode e
        JOIN e.media m
        WHERE e.media = :media
        ORDER BY e.pubDate DESC'
            )
            ->setParameter('media', $media)
            ->setFirstResult($start)
            ->setMaxResults($page_count);

        try {
            $paginator = new Paginator($query, $fetchJoinCollection = true);
            return $paginator;

        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function getLatestEpisodePubDate($media)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT e, m FROM HCMediaBundle:Episode e
          JOIN e.media m
          WHERE e.media = :media
          ORDER BY e.pubDate DESC'
            )->setParameter('media', $media)
            ->setFirstResult(0)
            ->setMaxResults(1);

        try {
            return $query->getResult();

        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function selectOldEpisodes($date)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM HCMediaBundle:Episode e
          WHERE e.pubDate < :date
          ORDER BY e.pubDate DESC'
            )->setParameter('date', $date);

        try {
            return $query->getResult();

        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }




}
